spring:
  datasource:
    url: jdbc:mysql://118.31.60.32:3306/phy_test?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: g06
    password: g06
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  database-platform: org.hibernate.dialect.H2Dialect
